import Head from "next/head";
import { useRouter } from "next/router";
import { signIn, useSession } from "next-auth/react";
import { useEffect } from "react";
import { Spinner } from "@radix-ui/themes";

function Home() {
	const router = useRouter();
	const { status } = useSession();


	if (status === "loading") {
		return <Spinner className="mx-auto" />;
	}
	
	return (
		<div>
			<Head>
				<title>Next Auth0 demo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-full h-screen flex items-center justify-center">
				<div className=" w-3/5 p-14 bg-gray-300 flex flex-col items-center justify-center rounded-md">
					<p>Sign In for enjoying our application pressing the Sign In button</p>
					<button
						className="font-semibold bg-blue-700 rounded-md text-white px-3 py-2 m-5 hover:bg-blue-800"
						onClick={() => {
							signIn("auth0", {
								callbackUrl: '/login'
							});
						}}
					>
						Sign in
					</button>
				</div>
			</div>
		</div>
	);
}
export default Home;
